class Movie{


  final List movieslist = [
    {
      "name":"The Girfield",
      "img_url": "https://www.saltypopcorn.co.uk/film-images/the-garfield-movie.jpg",
      "content_desc": "Garfield, the Monday-hating, lasagna-loving indoor cat, finds himself on a wild outdoor adventure when his long-lost father draws him into a high-stakes heist.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Over The Moon",
      "img_url":"https://collider.com/wp-content/uploads/2020/10/over-the-moon-album-cover.jpg",
      "content_desc":"Fueled by memories of her mother, resourceful Fei Fei builds a rocket to the moon on a mission to prove the existence of a legendary moon goddess.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"SPOOKIZ",
      "img_url":"https://i.ytimg.com/vi/HfEVEGf1A8Q/maxresdefault.jpg",
      "content_desc":"At an elementary school in the countryside where human children live during the day and monster children live at night, a human girl encounters the monster children after returning to retrieve the cell phone she left behind",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Valley of the Lanterns",
      "img_url":"https://i.ytimg.com/vi/lVsVmSmSAi8/maxresdefault.jpg",
      "content_desc":"An old woman's hold on the past puts her family's future in jeopardy.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"My FAMiLy",
      "img_url":"https://helios-i.mashable.com/imagery/articles/00Nz3CL4qF88c3H9tOks8LC/images-108.fill.size_2000x1081.v1633356007.jpg",
      "content_desc":"A man makes his way from Mexico to Los Angeles in the 1920s and gets married and raises a big family there. The movie follows the children until they get married and start their families in the 1960s",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Crow",
      "img_url":"https://i.ytimg.com/vi/NKq8vpCsDeA/maxresdefault.jpg",
      "content_desc":"The Crow is an American media franchise based on the limited comic book series of the same name created by James O'Barr. Since then, there have been five released films and a television series, as well as a video game.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"SPRING",
      "img_url":"https://tse4.mm.bing.net/th/id/OIP.1AhP5LODmGDHcApBTM6S7gHaEK?pid=Api&h=220&P=0",
      "content_desc":"Spring is a 2019 animated fantasy short film written and directed by Andreas Goralczyk and produced by Ton Roosendaal and Francesco Siddi. It is the Blender Institute's 12th, and was made utilizing the open-source software, Blender. ",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Hair Love",
      "img_url":"https://i.ytimg.com/vi/kNw8V_Fkw28/maxresdefault.jpg",
      "content_desc":"Hair Love is a 2019 American independent animated short film[1] directed by Matthew A. Cherry, Everett Downing Jr., and Bruce W. Smith, and written by Cherry. It follows the story of a man who must do his daughter's hair for the first time, and features Issa Rae as the voice of the mother.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"LAVA",
      "img_url":"https://i.pinimg.com/originals/91/af/53/91af532c00f4871d0926e9356a5e9322.jpg",
      "content_desc":"Lava is a 2014 American animated musical short film produced by Pixar Animation Studios.[2] Written and directed by James Ford Murphy and produced by Andrea Warren, it premiered at the Hiroshima International Animation Festival on June 14, 2014, and was theatrically released alongside Pixar's Inside Out, on June 19, 2015.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"WEEPING WILLOW",
      "img_url":"https://mir-s3-cdn-cf.behance.net/project_modules/1400/7682d629710335.5600617199fda.jpg",
      "content_desc":"Willow is a 1988 American high fantasy adventure film directed by Ron Howard and produced by Nigel Wooll. The film was executive produced by George Lucas and written by Bob Dolman from a story by Lucas. The film stars Warwick Davis as the title character, Val Kilmer, Joanne Whalley, Billy Barty and Jean Marsh.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"RAY GUNN",
      "img_url":"https://tse3.mm.bing.net/th/id/OIF.Su4RLoybaaHo4qzSj5Ks5g?pid=Api&h=220&P=0",
      "content_desc":"Ray Gunn is an upcoming American adult animated neo-noir cyberpunk science fiction mystery film directed by Brad Bird, who also wrote the original story and developed the script with Matthew Robbins",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"FLIGHT",
      "img_url":"https://tse1.mm.bing.net/th/id/OIP.AHDeTB5u8gy9XIQF1Y0KxwHaK-?pid=Api&h=220&P=0",
      "content_desc":"Flight is a 2012 American drama film directed by Robert Zemeckis, written by John Gatins and produced by Walter F. Parkes, Laurie MacDonald, Steve Starkey, Zemeckis, and Jack Rapke. ",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"25",
          "day":"Mon",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Prep & LANDING",
      "img_url":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/animated-christmas-movies-prep-and-landing-1565809593.jpg?crop=1xw:1xh;center,top&resize=480:*",
      "content_desc":"Prep & Landing is an American animated television special, based on an idea by Chris Williams at Walt Disney Animation Studios and developed by Kevin Deters and Stevie Wermers-Skelton into a half-hour Christmas special. ",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"24",
          "day":"sun",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
    {
      "name":"Light of the World",
      "img_url":"https://todayschristianent.com/wp-content/uploads/2025/07/LOTW_MoviePoster_croppedToFullSize1-scaled.jpg",
      "content_desc":"Follows Jesus' life from ministry beginnings through crucifixion, resurrection, as seen through Apostle John's eyes.",
      "dates":[
        {
          "date":"21",
          "day":"Thu",
          "times":["16:00","18:00","20:00"]
        },
        {
          "date":"22",
          "day":"Fri",
          "times":["17:00","19:00"]
        },
        {
          "date":"23",
          "day":"sat",
          "times":["16:00","18:00","20:00"]
        },
      ]
    },
  ];
}